name: mitoanalyzer-new
channels:
  - conda-forge
  - defaults
dependencies:
  - dask-core=2022.3.0
  - ffmpeg=4.3.1
  - graphviz=2.48.0
  - matplotlib=3.4.2
  - numpy=1.21.0
  - opencv=4.5.2
  - pandas=1.3.1
  - pip
  - prefect=1.1.0
  - python=3.9.6
  - python-graphviz=0.19.1
  - seaborn=0.11.2
  - scipy=1.10.0
  - pip:
    - nd2reader==3.3.0
    - networkx==2.5.1
    - scikit-image==0.18.2
    - tifffile==2021.7.2
    - tiffile==2018.10.18
