[project]
name = "mitosisanalyzer"
version = "0.0.1"
dependencies = [
    "pandas",
    "seaborn",
    "matplotlib",
    "argparse",
    "ffmpeg",
    "scipy",
    "scikit-image",
    "nd2reader",
    "tifffile",
    "tiffile",
    "typing",
    "opencv-python-headless",
    "cellpose",
    "prefect",
    "prefect-dask",
]
requires-python = ">=3.8"
description = "Tool to track spindle pole movements in fluorescently labeled mitotic cells."
readme = "README.md"
authors = [{ name = "Karsten Siller", email = "khs3z@virginia.edu }]
license = { file = "LICENSE" }
classifiers = [
    "Programming Language :: Python :: 3",
]
keywords = ["image processing", "segmentation", "data analytics", "workflow"]

[project.optional-dependencies]
napari = ["mitosisanalyzer-napari"]

[project.scripts]
mitoanalyzer = "mitosisanalyzer.analysis:main"

[project.gui-scripts]
mitoanalyzer = "mitosisanalyzer.analysis:main"

[project.urls]
Homepage = "https://github.com/uvarc/mitosisanalyzer"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
